### ISSUE TITLE
Error while adding an Overlay

### ISSUE THREAD

**Issue by Sukanyeah** [Rishikesht1245/Overlay_Module#1]
We're experiencing an error like this, while we tried to enable an overlay
![image](https://github.com/Rishikesht1245/Overlay_Module/assets/21282402/05cae065-e82c-45c6-89ea-bba58240ce99)

**Comment by Rishikesht1245** [comment]
Hello Ma'am,

 I've been reviewing the error and that seems to be related to database connection. Before proceeding further, I wanted to confirm with you whether there have been any error while connecting to the database.

Your clarification will be immensely helpful in troubleshooting and ensuring that the necessary updates are made promptly.

Thank you for your time.

**Comment by Sukanyeah** [comment]
This one still returns an error. Please refer the attached image.

Can you make necessary arrangements for the code to use MongoDB Compass instead of Atlas?
The Connection string is `mongodb://localhost:27017` and Database name is `overlay`

![image](https://github.com/Rishikesht1245/Overlay_Module/assets/21282402/4fe538fb-db8b-442b-827c-4699b885ebf7)

**Comment by Rishikesht1245** [comment]
Hi Ma'am,

It seems there might be an issue connecting to the local MongoDB instance. If you are testing locally, please replace the MONGO_URI with the connection string `mongodb://localhost:27017/overlay`. If the issue persists, consider replacing 'localhost' with the IP address of your local machine. 

Example:
```javascript
MONGO_URI='mongodb://localhost:27017/overlay'    or  MONGO_URI='mongodb://127.0.0.1:27017/overlay'
```
Could you please check and let me know if you still facing the issue.

**Comment by Sukanyeah** [comment]
Those settings were made earlier itself & still it wasn't working.

![image](https://github.com/Rishikesht1245/Overlay_Module/assets/21282402/081046b8-46e7-481a-b9d6-094450dccadb)

**Comment by Rishikesht1245** [comment]
Hello Ma'am,

To further investigate the issue, could you please provide the error message you're encountering on the server side after starting the server? If you receive a "database connected" success message, it would help narrow down whether the issue is related to the database or if there's another underlying issue.

**Comment by Sukanyeah** [comment]
Thank You
