### ISSUE TITLE
Errors while typing Inputs

### ISSUE THREAD

**Issue by Sukanyeah** [Rishikesht1245/Overlay_Module#2]
When we try to type anything on Title Input, it keeps on populating console errors.
![image](https://github.com/Rishikesht1245/Overlay_Module/assets/21282402/7e0b51b2-2e13-483d-b0a1-92e461acce1c)

**Comment by Rishikesht1245** [comment]
Hello Ma'am,

I have been investigating this issue within the update form section, and it appears that there might be an issue with the object retrieved from the database.

To gain a clearer understanding of the request and response in our API call, could you kindly provide screenshots of the network tab? I have already conducted necessary checks on the response object and updated the information on GitHub. However, having access to the network tab screenshots will greatly enhance clarity.

Your cooperation in providing this information is much appreciated. 

Thank you for your assistance.

**Comment by Rishikesht1245** [comment]
Hello Ma'am

After a comprehensive review of the issue you reported, I have identified it might be configuration-related issue related to the environment variables. It appears that there was a missed step in adding the API URL to the environment variables (I missed this step to mention in the readme file ).

To address this, I have made the necessary adjustments. You can now test the solution by visiting the live link: [Live Link](https://overlay-module.onrender.com/)

**Comment by Sukanyeah** [comment]
Thanks for the prompt reply @Rishikesht1245 

This issue seems to be fixed.
